[[plugins]]
repo = 'vim-jp/vimdoc-ja'
[[plugins]]
repo = 'lambdalisue/fern.vim'
[[plugins]]
repo = 'habamax/vim-gruvbit'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'junegunn/fzf'
[[plugins]]
repo = 'junegunn/fzf.vim'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'machakann/vim-highlightedyank'
[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
  let g:fern#renderer = 'nerdfont'
'''
[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup END
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
